#!/bin/sh

ENABLED=yes

DESC="BitTorrent Protocol Daemon"
PROCS="btpd"
PROG="/opt/bin/$PROCS"

PID_FILE="/opt/downloads/$PROCS/pid"

pre_cmd() {
  rm -f "$PID_FILE"
}

PRECMD="pre_cmd"
ARGS="-d /opt/downloads/$PROCS --empty-start"
PREARGS=""

. /opt/etc/init.d/rc.func
