#!/bin/sh

ENABLED=yes

DESC="Port-knocking"
PROCS="knockd"
PROG="/opt/sbin/$PROCS"

PID_FILE="/opt/var/run/$PROCS.pid"

pre_cmd() {
  rm -f "PID_FILE"
}

PRECMD="pre_cmd"
ARGS="-d -v"
PREARGS=""

. /opt/etc/init.d/rc.func
